//stadium IDs
const stadiumid = ["1","2","3","4","5","6","7","3312","9","10","11","12","13","14","15","4705","17","18","19","20","21","22","23","25","26","27","28","29","2889","31","32","3309"];

//css IDs
const cssids =
["laa","bal","bos","chw","cle","det","kan","min","nyy","oak","sea","tbr","txr","tor","ari","atl","chc","cin","col","mia","hou","lad","nym","phi","sdp","sfg","slc","pit","mil","was"];

// team names
const teams = ["Angel Stadium (Los Angeles Angels)","Oriole Park at Camden Yards (Baltimore Orioles)","Fenway Park (Boston Red Sox)","Guaranteed Rate Field (Chicago White Sox)","Progressive Field (Cleveland Guardians)","Tiger Stadium (Detroit Tigers)","Kauffman Stadium (Kansas City Royals)","Target Field (Minnesota Twins)","Yankee Stadium (New York Yankees)","Oakland Coliseum (Oakland Athletics)","The Kingdome (Seattle Mariners)","Tropicana Field (Tamba Bay Rays)","Choctaw Stadium (Texas Rangers)","Rogers Centre (Toronto Blue Jays)","Chase Field (Arizona Diamondbacks)","Turner Field (Atlanta Braves)","Wrigley Field (Chicago Cubs)","Cinergy Field (Cincinnati Reds)","Coors Field (Colorado Rockies)","Hard Rock Stadium (Floria Marlins)","Astrodome (Houston Astros)","Dodger Stadium (Los Angeles Dodgers)","Shea Stadium (New York Mets)","Veterans Stadium (Philadelphia Phillies)","Qualcomm Stadium (San Diego Padres)","3Com Park at Candlestick Point (San Francisco Giants)","Busch Stadium (St. Louis Cardinals)","PNC Park (Pittsburgh Pirates)","American Family Field (Milwaukee Brewers)","Nationals Park (Washington Nationals)"];

let teamjpgs = ["LAA.jpg","BAL.jpg","BOS.jpg","CWS.jpg","CLE.jpg","DET.jpg","KAN.jpg","MIN.jpg","NYY.jpg","OAK.jpg","SEA.jpg","TAM.jpg","TEX.jpg","TOR.jpg","ARI.jpg","ATL.jpg","CHC.jpg","CIN.jpg","COL.jpg","FLA.jpg","HOU.jpg","LAD.jpg","NYM.jpg","PHI.jpg","SD.jpg","SF.jpg","STL.jpg","PIT.jpg","MIL.jpg","WAS.jpg"];

let teampngs = ["LAA","BAL","BOS","CWS","CLE","DET","KAN","MIN","NYY","OAK","SEA","TAM","TEX","TOR","ARI","ATL","CHC","CIN","COL","FLA","HOU","LAD","NYM","PHI","SD","SF","STL","PIT","MIL","WAS"];

let teamlogos = ["los-angeles-angels-logo-transparent.png","baltimore-orioles-bird-logo.png","boston-red-sox-logo-transparent.png","chicago-white-sox-logo-transparent.png","cleveland-indians-c-logo-transparent.png","detroit-tigers-logo-transparent.png","kansas-city-royals-crown-logo.png","minnesota-twins-logo-transparent.png","new-york-yankees-logo-transparent.png","oakland-athletics-logo-transparent.png","seattle-mariners-logo-transparent.png","tampa-bay-rays-logo-transparent.png","texas-rangers-logo-transparent.png","toronto-blue-jays-logo-transparent.png","arizona-diamondbacks-logo-transparent.png","atlanta-braves-baseball-logo.png","chicago-cubs-logo-transparent.png","cincinnati-reds-logo-transparent.png","colorado-rockies-logo-transparent.png","miami-marlins-logo-transparent.png","houston-astros-logo-transparent.png","los-angeles-dodgers-logo-transparent.png","new-york-mets-logo-transparent.png","philadelphia-phillies-logo-transparent.png","san-diego-padres-logo-transparent.png","san-francisco-giants-logo-transparent.png","st-louis-cardinals-logo-transparent.png","pittsburgh-pirates-logo-transparent.png","milwaukee-brewers-logo-transparent.png","washington-nationals-logo-transparent.png"]